[package]
name = "lex-checker"
version = "0.1.0"
authors = ["Artem Sergeev"]
edition = "2024"
publish = false

[dependencies]
log = "0.4.28"
rand = "0.9.2"
inquire = "0.9.1"
config = "0.15.18"
anyhow = "1.0.100"
env_logger = "0.11.8"
serde = { version = "1.0.228", features = ["derive"] }
